type = "javascript"
zone_id = "a7bc6d72d8d7927ad1a49d855cfad6c6" # polyratings.dev
account_id = "4b59b59a6058dce1832781075d4fde9d"
usage = "bundled"
workers_dev = false
compatibility_date = "2022-01-15"

[build]
command = "npm run build"

[build.upload]
format = "modules"
dir = 'dist'
main = './index.js' # TODO: figure out what actually goes here!!

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]

# TODO: Change env.sunder and env.dev to use non-prod datasets
[env.dev]
name = 'dev-backend'
route = 'api-dev.polyratings.dev/*'
usage = "bundled"
kv_namespaces = [
    { binding = "POLYRATINGS", id = "c6bf2730306a4e65bb8aa7412ae6f250", preview_id = "1c0b9ffba23c46f2928b7af696de1862"},
    { binding = "PROCESSING_QUEUE", id = "845ba14e564c411fa52543408e15c53e", preview_id = "7efebba0f4d04f369066284dd9749ed4"},
    { binding = "POLYRATINGS_USERS", id = "a23f7444e3c34913b7f04223fd1920d3", preview_id = "a23f7444e3c34913b7f04223fd1920d3"},
    { binding = "POLYRATINGS_TEACHER_APPROVAL_QUEUE", id = "6adc0bac1438487f82de330b94684e73", preview_id = "6adc0bac1438487f82de330b94684e73"}
]

[env.beta]
name = 'beta-backend'
route = 'api-beta.polyratings.dev/*'
usage = "bundled"
kv_namespaces = [
    { binding = "POLYRATINGS", id = "c6bf2730306a4e65bb8aa7412ae6f250", preview_id = "1c0b9ffba23c46f2928b7af696de1862"},
    { binding = "PROCESSING_QUEUE", id = "845ba14e564c411fa52543408e15c53e", preview_id = "7efebba0f4d04f369066284dd9749ed4"},
    { binding = "POLYRATINGS_USERS", id = "a23f7444e3c34913b7f04223fd1920d3", preview_id = "a23f7444e3c34913b7f04223fd1920d3"},
    { binding = "POLYRATINGS_TEACHER_APPROVAL_QUEUE", id = "6adc0bac1438487f82de330b94684e73", preview_id = "6adc0bac1438487f82de330b94684e73"}
]

[env.prod]
name = "prod-backend"
route = "api-prod.polyratings.dev/*"
usage = "bundled"
kv_namespaces = [
    { binding = "POLYRATINGS", id = "c6bf2730306a4e65bb8aa7412ae6f250", preview_id = "1c0b9ffba23c46f2928b7af696de1862"},
    { binding = "PROCESSING_QUEUE", id  = "845ba14e564c411fa52543408e15c53e", preview_id = "7efebba0f4d04f369066284dd9749ed4"},
    { binding = "POLYRATINGS_USERS", id = "a23f7444e3c34913b7f04223fd1920d3", preview_id = "a23f7444e3c34913b7f04223fd1920d3"},
    { binding = "POLYRATINGS_TEACHER_APPROVAL_QUEUE", id = "6adc0bac1438487f82de330b94684e73", preview_id = "6adc0bac1438487f82de330b94684e73"}
]

[dev]
port = 8080
local_protocol = "https"
