name: Continuous Integration and Deployment

on: [push]

jobs:
  Integration_And_Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Install Top Level Dependencies
        run: |
          npm ci
      
      - name: Install Dependencies
        run: |
          npm run bootstrap

      - name: Build Packages
        run: |
          npm run build

      - name: Test Packages
        run: |
          npm run test

      - name: Deploy Prod
        if: github.ref == 'refs/heads/master'
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          npm run deploy:prod

      - name: Deploy Beta
        if: github.ref == 'refs/heads/beta'
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          npm run deploy:beta