name: Continuous Integration and Deployment

on: [push]

jobs:
  Integration_And_Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Install Top Level Dependencies
        run: |
          npm ci
      
      - name: Install Dependencies
        run: |
          npm run bootstrap

      - name: Lint packages
        run: |
          npm run lint

      - name: Build Packages
        run: |
          npm run build

#      - name: Test Packages
#        run: |
#          npm run test

      - name: Deply to CloudFront
        if: github.reg == 'refs/heads/master'
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          POLYRATINGS_DISTRIBUTION_ID: ${{ secrets.POLYRATINGS_DISTRIBUTION_ID }}
          POLYRATINGS_S3_URI: ${{ secrets.POLYRATINGS_S3_URI }}
        run: |
          ./cloudfront-deploy.sh

#      - name: Deploy Prod
#        if: github.ref == 'refs/heads/master'
#        env:
#          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
#        run: |
#          npm run deploy:prod
#
#      - name: Deploy Beta
#        if: github.ref == 'refs/heads/beta'
#        env:
#          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
#        run: |
#          npm run deploy:beta
